tclock/src/e_mod_config.c
Sorry, I could push directly...
=> TClock color selector added

alarm/configure.ac, calendar/configure.ac, cpu/configure.ac, deskshow/configure.ac, diskio/configure.ac, engage/configure.ac, flame/configure.ac, forecasts/configure.ac, mail/configure.ac, mem/configure.ac, net/configure.ac, news/configure.ac, penguins/configure.ac, photo/configure.ac, places/configure.ac, rain/configure.ac, screenshot/configure.ac, share/configure.ac, slideshow/configure.ac, snow/configure.ac, tclock/configure.ac, trash/configure.ac, winlist-ng/configure.ac, winselector/configure.ac
This pairs with a similar change from Moksha, commit
eb1594e8836afff48f9a04aac63c8128e07b12d6.
=> Remove Moksha version from MODULE_ARCH

trash/module.desktop.in, trash/po/LINGUAS, trash/po/fr.po
=> French translations for the trash module

forecasts/po/fr.po, mail/po/fr.po, news/po/fr.po, tclock/po/fr.po, winlist-ng/po/LINGUAS, winlist-ng/po/fr.po
=> French translations update

mem/module.desktop.in, screenshot/module.desktop.in, tclock/module.desktop.in
Modules: mem, screenshot, tclock.
=> Belarusian translation for module.desktop.in

calendar/module.desktop.in, calendar/po/LINGUAS, calendar/po/be.po, cpu/module.desktop.in, cpu/po/LINGUAS, cpu/po/be.po, deskshow/module.desktop.in, diskio/module.desktop.in
Modules translated: calendar, cpu, deskshow, diskio.
=> Belarusian translation

photo/po/be.po, photo/po/ru.po, rain/module.desktop.in, rain/po/LINGUAS, rain/po/be.po, snow/module.desktop.in, snow/po/LINGUAS, snow/po/be.po, trash/module.desktop.in, trash/po/LINGUAS, trash/po/be.po, trash/po/ru.po
Belarusian translations for modules: rain, snow, trash.
Russian translation for module: trash.
=> Belarusian (and some Russian) translations.

winlist-ng/module.desktop.in, winlist-ng/po/LINGUAS, winlist-ng/po/be.po, winlist-ng/po/ru.po, winselector/module.desktop.in
Belarusian translation for modules winlist-ng and winselector.
Russian translation for module winlist-ng.
=> Belarusian (and some Russian) translation

modules/engage/po/pt.po
* Update `pt.po` file
* Minor corrections
=> ENGAGE: Update Portuguese translation

modules/mail/po/pt.po, modules/photo/po/pt.po, modules/slideshow/po/pt.po, modules/tclock/po/pt.po
Portuguese translations update for the following modules:
* Tclock
* Slideshow
* Photo
* Mail
=> Update portuguese translations

modules/slideshow/po/pt.po
* Update Portuguese translation
* Other minor improvements
=> Slideshow: pt.po update

modules/alarm/po/pt.po, modules/engage/po/LINGUAS, modules/trash/po/LINGUAS, modules/winlist-ng/po/LINGUAS
* `alarm` : fix typo an improve pt.po file
* `engage` `trash` `winlist-ng` : sort lang codes alphabetically in `LINGUAS` file
=> Update alarm pt.po and sort lang codes alphabetically

modules/winselector/po/LINGUAS, modules/winselector/po/it.po, modules/winselector/po/pl.po
'it.pl' translated. 'pl.po' created.
=> 'it' and 'pl' patch

modules/tclock/po/pt.po
Word `Portuguese` written in duplicate
=> Tclock: clean up pt.po file

modules/mail/module.desktop.in, modules/mail/po/it.po, modules/mail/po/pl.po
=> IT - PL patch for mail module

modules/wallscape/po/it.po, modules/wallscape/po/pl.po
=> IT - PL patch v.2 for wallscape module 

modules/alarm/po/de.po
Review of de.po in modules/alarm
=> de.po  updated

modules/cpu/po/de.po
Review of de.po in modules/cpu
=> Updated de.po

modules/diskio/po/de.po, modules/engage/po/de.po, modules/flame/po/de.po, modules/mail/po/de.po
Updated de.po files for several modules
=> Updated de.po files

modules/alarm/po/pt.po
=> Update portuguese translation

modules/slideshow/po/de.po, modules/tclock/po/de.po, modules/wallscape/po/de.po, modules/winselector/po/de.po
=> Updated the missing de.po files

modules/alarm/po/LINGUAS, modules/alarm/po/mr.po
=> added mr for alarm module

modules/penguins/po/mr.po, modules/photo/po/mr.po
Marathi Language_India for Extras Modules Penguins and Photo
=> mr.po for penguins and photo module
